kind: Deployment
apiVersion: apps/v1
metadata:
  name: echo
  namespace: camunda-workers
  labels:
    app: digit-plattform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
        app.kubernetes.io/name: echo
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
        - name: echo
          image: ghcr.io/haninge-digit/digit-worker-echo:main   # Set tag to "lab" for lab versions and "latest" for production versions
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: 'false'  # Change to 'true' for debugging
            - name: ZEEBE_ADDRESS
              value: camunda-zeebe-gateway.camunda-zeebe:26500
            - name: USERINFOCASH
              value: userinfocash:8080
            - name: KIR_URL
              valueFrom:
                secretKeyRef:
                  name: kir-secret
                  key: KIR_URL
            - name: KIR_USER
              valueFrom:
                secretKeyRef:
                  name: kir-secret
                  key: KIR_USER
            - name: KIR_PWD
              valueFrom:
                secretKeyRef:
                  name: kir-secret
                  key: KIR_PWD
            - name: AD_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: ms365ad-secret
                  key: AD_TENANT_ID
            - name: AD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ms365ad-secret
                  key: AD_CLIENT_ID
            - name: AD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ms365ad-secret
                  key: AD_CLIENT_SECRET
            - name: MONGO_ROOT_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
          resources:    # Might need to be tailored
            limits:
              memory: "128Mi"
              cpu: "100m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext: {}
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
